server:
  port: 8081

spring:
  application:
    name: LoanServiceExample
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
  sql:
    init:
      mode: embedded
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5

loan:
  constraints:
    minInput: 2000
    maxInput: 10000
    minOutput: 2000
    maxOutput: 10000
    minPeriod: 12
    maxPeriod: 60
